# Generated by Django 3.1.5 on 2021-02-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_model',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Note_model',
            new_name='NoteModel',
        ),
    ]
